# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=32, verbose_name='user id')),
                ('click_area', models.CharField(max_length=100, null=True, verbose_name='Click area name')),
                ('user_agent', models.CharField(max_length=100)),
                ('user_os', models.CharField(max_length=50, null=True, verbose_name="user's OS")),
                ('user_browser', models.CharField(max_length=50, null=True, verbose_name="user's browser")),
                ('ip_address', models.GenericIPAddressField()),
                ('http_headers', models.TextField()),
                ('request_path', models.CharField(max_length=256)),
                ('additional_info', models.TextField(null=True, verbose_name='additional information')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.CharField(max_length=32)),
            ],
        ),
    ]
