# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-07-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_auto_20200130_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='registration',
            name='lastName',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
