# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-07-17 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_auto_20200717_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='firstName',
            new_name='name',
        ),
    ]
